# content of pytest.ini
[pytest]
markers =
    failing_on_rocm: Currently Failing Tests on ROCm.
    failing_on_rocm_mi250: Tests failing on MI250.
    failing_on_upstream: Failing on upsteam.
    flaky_in_dev: Flaky tests in development.
    internal: Mark a test as a test to private/internal functions.
    test_on_rocm: Tests run on ROCm specifically.
    timeout: Mark a test with a timeout.
addopts =
    ; --color yes
    --csv output/test_report.csv
    --dist loadscope
    --ignore tests/unit_tests/test_utilities.py
    -s
